name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check current directory
      run: pwd

    - name: List files in current directory
      run: ls -a

    - name: Move to project directory (if needed)
      run: cd yatt  # 必要に応じて適切なディレクトリ名に変更

    - name: Ensure gradlew is executable
      run: chmod +x gradlew

    - name: Run lintRelease
      run: ./gradlew lintRelease
