name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
      
    - name: generate wapper
      run: gradle wrapper

    - name: Ensure gradlew is executable
      run: chmod +x gradlew

    - name: Run lintRelease
      run: ./gradlew lintRelease
